language: node_js
node_js: 
 - "stable"
cache:
  directories: 
  - node_modules
script: 
- npm install
- npm test
- npm run build


deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: github.com/react-test-app
  bucket: tests3buckets3
  region: us-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tests3buckets3
  key: latest.zip
  bundle_type: zip
  application: react-test-app
  deployment_group: react
  region: us-west-1
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

